apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: sample-frontend
spec:
  selector:                                               # 2
    matchLabels:
      app: sample-frontend                                    
  replicas: 2                                             # 3
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 4
    rollingUpdate: 
      maxUnavailable: 1                                   # 5
      maxSurge: 1                                         # 6
  template:                                               # 7
    metadata:
      labels:
        app: sample-frontend                              # 8
    spec:
      containers:
        - image: w1sh3r/sample-frontend
          imagePullPolicy: Always                         # 9
          name: sample-frontend
          ports:
            - containerPort: 80