apiVersion: v1
kind: Pod
metadata:
  name: sample-frontend2   # the only change
  labels:
     app: sample-frontend
spec:
  containers:
    - image: w1sh3r/sample-frontend
      name: sample-frontend
      ports:
      - containerPort: 80